import {selectors} from "../selectors/selectors";
import {notifications} from "../selectors/notifications";

let sumForPay = 300;
let sumForRequest = 500;
let messageP = 'Your transaction payment';
let messageR = 'Your transaction request';

const userA = {
    username: "Katharina Bernier",
    name: "Abra Kadabra"
}

const userB = {
    username: "Tavares Barrows",
    name: "Arely Kertzmann"
}

const userС = {
    username: "Allie2",
    name: "Kaylin Homenick"
}

describe('tests for notification', () => {

    beforeEach("signin", () => {
        cy.visit('/')
        cy.intercept('POST', '/login').as('login')
        cy.intercept('POST', '/graphql').as('graphql')
        cy.intercept('GET', '/notifications').as('notifications')
        cy.intercept('GET', '/users').as('users')
        cy.intercept('POST', '/transactions').as('transactions')
        cy.intercept('GET', '/checkAuth').as('checkAuth')
        cy.intercept('POST', '/likes/*').as('like')
        cy.intercept('POST', '/logout').as('logout')
        cy.intercept('GET', '/transactions').as('transaction')
    })

    it('When user A likes a transaction of user B, user B should get notification that user A liked transaction', () => {
        cy.loginByApi("Tavares_Barrows", "s3cret")
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(selectors.btnCreateNewTransaction).click()
        cy.wait('@users')
        cy.get(selectors.transactionList).should("be.visible").contains('Abra Kadabra').click({force: true});
        cy.get(selectors.amountField).type(sumForRequest)
        cy.get(selectors.addANoteField).type(messageR)
        cy.get(selectors.requestBtn).click()
        cy.wait('@transactions')
        cy.get(selectors.returnToTransactionsBtn).click()
        cy.wait('@checkAuth')
        cy.get(selectors.messageTransactionSubmitted).should('be.visible').should('have.text', 'Transaction Submitted!')
        cy.logoutApi()
        cy.wait('@logout')
        cy.loginByApi("Katharina_Bernier", "s3cret")
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(notifications.transactionList).contains(`${userB.name} requested ${userA.name}`).first().click({force: true})
        cy.get(notifications.likeButton).click()
        cy.wait('@like')
        cy.logoutApi()
        cy.wait('@logout')
        cy.loginByApi("Tavares_Barrows", "s3cret")
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(notifications.notificationBtn).click()
        cy.wait('@notifications')
        cy.get(notifications.notificationslist).should("contain", `${userA.name} liked a transaction`);
        cy.logoutApi()
        cy.wait('@logout')
    })

    it('When user C likes a transaction between user A and user B, user A and user B should get notifications that user C liked transaction', () => {
        cy.loginByApi("Katharina_Bernier", "s3cret")
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(selectors.btnCreateNewTransaction).click()
        cy.wait('@users')
        cy.get(selectors.transactionList).should("be.visible").contains('Arely Kertzmann').click({force: true});
        cy.get(selectors.amountField).type(sumForRequest)
        cy.get(selectors.addANoteField).type(messageR)
        cy.get(selectors.requestBtn).click()
        cy.wait('@transactions')
        cy.get(selectors.returnToTransactionsBtn).click()
        cy.wait('@checkAuth')
        cy.get(selectors.messageTransactionSubmitted).should('be.visible').should('have.text', 'Transaction Submitted!')
        cy.logoutApi()
        cy.wait('@logout')
        cy.loginByApi("Allie2", "s3cret")
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(notifications.transactionList).contains(`${userA.name} requested ${userB.name}`).first().click({force: true})
        cy.get(notifications.likeButton).click()
        cy.wait('@like')
        cy.logoutApi()
        cy.wait('@logout')
        cy.loginByApi("Katharina_Bernier", "s3cret")
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(notifications.notificationBtn).click()
        cy.get(notifications.notificationslist).contains(`${userС.name} liked a transaction.`)
        cy.logoutApi()
        cy.wait('@logout')
        cy.loginByApi("Tavares_Barrows", "s3cret")
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(notifications.notificationBtn).click()
        cy.get(notifications.notificationslist).contains(`${userС.name} liked a transaction.`)
        cy.logoutApi()
        cy.wait('@logout')
    })

    it(' When user A comments on a transaction of user B, user B should get notification that User A commented on their transaction', () => {
        cy.loginByApi("Tavares_Barrows", "s3cret")
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(selectors.btnCreateNewTransaction).click()
        cy.wait('@users')
        cy.get(selectors.transactionList).should("be.visible").contains('Abra Kadabra').click({force: true});
        cy.get(selectors.amountField).type(sumForRequest)
        cy.get(selectors.addANoteField).type(messageR)
        cy.get(selectors.requestBtn).click()
        cy.wait('@transactions')
        cy.get(selectors.returnToTransactionsBtn).click()
        cy.wait('@checkAuth')
        cy.get(selectors.messageTransactionSubmitted).should('be.visible').should('have.text', 'Transaction Submitted!')
        cy.logoutApi()
        cy.wait('@logout')
        cy.loginByApi("Katharina_Bernier", "s3cret")
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(notifications.transactionList).contains(`${userB.name} requested ${userA.name}`).first().click({force: true})
        cy.get(notifications.commentField).type('Bro').type('{enter}')
        cy.logoutApi()
        cy.wait('@logout')
        cy.loginByApi("Tavares_Barrows", "s3cret")
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(notifications.notificationBtn).click()
        cy.get(notifications.notificationslist).contains(`${userA.name} commented on a transaction.`)
        cy.wait('@notifications')
        cy.logoutApi()
        cy.wait('@logout')
    })

    it('When user C comments on a transaction between user A and user B, user A and B should get notifications that user C commented on their transaction', () => {
        cy.loginByApi("Katharina_Bernier", "s3cret")
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(selectors.btnCreateNewTransaction).click()
        cy.wait('@users')
        cy.get(selectors.transactionList).should("be.visible").contains('Arely Kertzmann').click({force: true});
        cy.get(selectors.amountField).type(sumForRequest)
        cy.get(selectors.addANoteField).type(messageR)
        cy.get(selectors.requestBtn).click()
        cy.wait('@transactions')
        cy.get(selectors.returnToTransactionsBtn).click()
        cy.wait('@checkAuth')
        cy.get(selectors.messageTransactionSubmitted).should('be.visible').should('have.text', 'Transaction Submitted!')
        cy.logoutApi()
        cy.wait('@logout')
        cy.loginByApi("Allie2", "s3cret")
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(notifications.transactionList).contains(`${userA.name} requested ${userB.name}`).first().click({force: true})
        cy.get(notifications.commentField).type('GOOD').type('{enter}')
        cy.logoutApi()
        cy.wait('@logout')
        cy.loginByApi("Katharina_Bernier", "s3cret")
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(notifications.notificationBtn).click()
        cy.get(notifications.notificationslist).contains(`${userС.name} liked a transaction.`)
        cy.wait('@notifications')
        cy.logoutApi()
        cy.wait('@logout')
        cy.loginByApi("Tavares_Barrows", "s3cret")
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(notifications.notificationBtn).click()
        cy.get(notifications.notificationslist).contains(`${userС.name} liked a transaction.`)
        cy.wait('@notifications')
        cy.logoutApi()
        cy.wait('@logout')
    })

    it('When user A sends a payment to user B, user B should be notified of payment', () => {
        cy.loginByApi("Katharina_Bernier", "s3cret")
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(selectors.btnCreateNewTransaction).click()
        cy.wait('@users')
        cy.get(selectors.transactionList).should("be.visible").contains('Arely Kertzmann').click({force: true});
        cy.get(selectors.amountField).type(sumForPay)
        cy.get(selectors.addANoteField).type(messageP)
        cy.get(selectors.payBtn).click()
        cy.wait('@transactions')
        cy.get(selectors.returnToTransactionsBtn).click()
        cy.wait('@checkAuth')
        cy.get(selectors.messageTransactionSubmitted).should('be.visible').should('have.text', 'Transaction Submitted!')
        cy.logoutApi()
        cy.wait('@logout')
        cy.loginByApi("Tavares_Barrows", "s3cret")
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(notifications.notificationBtn).click()
        cy.get(notifications.notificationslist).contains(`${userB.name} received payment.`)
        cy.get(notifications.logout_btn).click()
        cy.logoutApi()
        cy.wait('@logout')
    })

    it('When user A sends a payment request to user C, user C should be notified of request from user A', () => {
        cy.loginByApi("Katharina_Bernier", "s3cret")
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(selectors.btnCreateNewTransaction).click()
        cy.wait('@users')
        cy.get(selectors.transactionList).should("be.visible").contains('Kaylin Homenick').click({force: true});
        cy.get(selectors.amountField).type(sumForPay)
        cy.get(selectors.addANoteField).type(messageP)
        cy.get(selectors.requestBtn).click()
        cy.wait('@transactions')
        cy.get(selectors.returnToTransactionsBtn).click()
        cy.wait('@checkAuth')
        cy.get(selectors.messageTransactionSubmitted).should('be.visible').should('have.text', 'Transaction Submitted!')
        cy.logoutApi()
        cy.wait('@logout')
        cy.loginByApi("Allie2", "s3cret")
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(notifications.notificationBtn).click()
        cy.get(notifications.notificationslist).contains(`${userA.name} requested payment.`)
        cy.logoutApi()
        cy.wait('@logout')
    })
})