import {selectors, dataForSignUp, dataForLoginTransaction, dataForLoginReceiver} from "../selectors/selectors";
import {dataForLoginUserA, dataForLoginUserB, dataForLoginUserC, notifications} from "../selectors/notifications";

describe('tests for notification', () => {

    beforeEach("signin", () => {
        cy.visit('/')
        cy.intercept('POST', '/login').as('login')
        cy.intercept('POST', '/graphql').as('graphql')
        cy.intercept('GET', '/notifications').as('notifications')
        cy.intercept('GET', '/users').as('users')
        cy.intercept('POST', '/transactions').as('transactions')
        cy.intercept('GET', '/checkAuth').as('checkAuth')
        cy.intercept('POST', '/likes/*').as('like')
        cy.intercept('POST', '/logout').as('logout')
        cy.intercept('GET', '/transactions').as('transaction')
    })

    it('transactions navigation tabs should be hidden on a transaction view page', () => {
        cy.get(selectors.username).type(dataForLoginUserB.usernameForUserB)
        cy.get(selectors.password).type(dataForLoginUserB.passwordForUserB)
        cy.get(selectors.signIn).click()
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(notifications.transactionList).first().click()
        cy.get(selectors.btnEveryone).should("not.exist")
        cy.get(selectors.btnFriends).should("not.exist")
        cy.get(selectors.btnMine).should("not.exist")
        cy.get(notifications.logout_btn).click()
        cy.wait('@logout')
    })

    it('User should be able to like a transaction', () => {
        cy.get(selectors.username).type(dataForLoginUserB.usernameForUserB)
        cy.get(selectors.password).type(dataForLoginUserB.passwordForUserB)
        cy.get(selectors.signIn).click()
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(selectors.btnCreateNewTransaction).click()
        cy.wait('@users')
        cy.get(selectors.transaction_list).should("be.visible").contains('Edgar Johns').click()
        cy.get(selectors.amountField).type('500')
        cy.get(selectors.addANoteField).type('Money')
        cy.get(selectors.requestBtn).click()
        cy.wait('@transactions')
        cy.get(notifications.logout_btn).click()
        cy.wait('@logout')
        cy.get(selectors.username).type(dataForLoginUserA.usernameForUserA)
        cy.get(selectors.password).type(dataForLoginUserA.passwordForUserA)
        cy.get(selectors.signIn).click()
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(notifications.transactionList).first().click()
        cy.get(notifications.likeButton).click()
        cy.wait('@like')
    })

    it('User should be able to comment on a transaction', () => {
        cy.get(selectors.username).type(dataForLoginUserB.usernameForUserB)
        cy.get(selectors.password).type(dataForLoginUserB.passwordForUserB)
        cy.get(selectors.signIn).click()
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(selectors.btnCreateNewTransaction).click()
        cy.wait('@users')
        cy.get(selectors.transaction_list).should("be.visible").contains('Edgar Johns').click()
        cy.get(selectors.amountField).type('500')
        cy.get(selectors.addANoteField).type('Money')
        cy.get(selectors.requestBtn).click()
        cy.wait('@transactions')
        cy.get(notifications.logout_btn).click()
        cy.wait('@logout')
        cy.get(selectors.username).type(dataForLoginUserA.usernameForUserA)
        cy.get(selectors.password).type(dataForLoginUserA.passwordForUserA)
        cy.get(selectors.signIn).click()
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(notifications.transactionList).first().click()
        cy.get(notifications.commentField).type('some text').type('{enter}')
        cy.get(notifications.logout_btn).click()
        cy.wait('@logout')
    })

    it('User should be able to accept a transaction request', () => {
        cy.get(selectors.username).type(dataForLoginUserB.usernameForUserB)
        cy.get(selectors.password).type(dataForLoginUserB.passwordForUserB)
        cy.get(selectors.signIn).click()
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(selectors.btnCreateNewTransaction).click()
        cy.wait('@users')
        cy.get(selectors.transaction_list).should("be.visible").contains('Edgar Johns').click()
        cy.get(selectors.amountField).type('500')
        cy.get(selectors.addANoteField).type('Money')
        cy.get(selectors.requestBtn).click()
        cy.wait('@transactions')
        cy.get(notifications.logout_btn).click()
        cy.wait('@logout')
        cy.get(selectors.username).type(dataForLoginUserA.usernameForUserA)
        cy.get(selectors.password).type(dataForLoginUserA.passwordForUserA)
        cy.get(selectors.signIn).click()
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(notifications.transactionList).first().click()
        cy.get(selectors.acceptRequestBtn).click({ force: true })
    })

    it('User should be able to reject a transaction request', () => {
        cy.get(selectors.username).type(dataForLoginUserB.usernameForUserB)
        cy.get(selectors.password).type(dataForLoginUserB.passwordForUserB)
        cy.get(selectors.signIn).click()
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(selectors.btnCreateNewTransaction).click()
        cy.wait('@users')
        cy.get(selectors.transaction_list).should("be.visible").contains('Edgar Johns').click()
        cy.get(selectors.amountField).type('500')
        cy.get(selectors.addANoteField).type('Money')
        cy.get(selectors.requestBtn).click()
        cy.wait('@transactions')
        cy.get(notifications.logout_btn).click()
        cy.wait('@logout')
        cy.get(selectors.username).type(dataForLoginUserA.usernameForUserA)
        cy.get(selectors.password).type(dataForLoginUserA.passwordForUserA)
        cy.get(selectors.signIn).click()
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(notifications.transactionList).first().click()
        cy.get(selectors.rejectBtn).click({ force: true })
    })

    it('Accept/reject buttons shouldn\'t exist on completed request', () => {
        cy.get(selectors.username).type(dataForLoginUserB.usernameForUserB)
        cy.get(selectors.password).type(dataForLoginUserB.passwordForUserB)
        cy.get(selectors.signIn).click()
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(selectors.btnCreateNewTransaction).click()
        cy.wait('@users')
        cy.get(selectors.transaction_list).should("be.visible").contains('Edgar Johns').click()
        cy.get(selectors.amountField).type('500')
        cy.get(selectors.addANoteField).type('Money')
        cy.get(selectors.requestBtn).click()
        cy.wait('@transactions')
        cy.get(notifications.logout_btn).click()
        cy.wait('@logout')
        cy.get(selectors.username).type(dataForLoginUserA.usernameForUserA)
        cy.get(selectors.password).type(dataForLoginUserA.passwordForUserA)
        cy.get(selectors.signIn).click()
        cy.wait('@login')
        cy.wait('@graphql')
        cy.wait('@notifications')
        cy.get(notifications.transactionList).first().click()
        cy.get(selectors.acceptRequestBtn).should("be.enabled")
        cy.get(selectors.rejectBtn).should("be.enabled")
        cy.get(selectors.rejectBtn).click({ force: true })
        cy.get(selectors.acceptRequestBtn).should("not.exist")
        cy.get(selectors.rejectBtn).should("not.exist")
        cy.get(notifications.logout_btn).click()
        cy.wait('@logout')
    })
})